services:
  postgres:
    image: postgres:latest
    container_name: api-postgres
    ports:
      - "5434:5432" # porta alterada para evitar conflito com outro projeto
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mpbarber
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
